### ISSUE TITLE
Help, with the connect elixir and react 

### ISSUE THREAD

**Issue by aquicreamos** [onerciller/react-redux-laravel#1]
Hola you can could connect elixir and react; I do not know how to do it, you can help please share your files connection node-modules, and elixir?

**Comment by onerciller** [comment]
Hi obviously, I have never done it that something like that. I don't know as well how to do it. if I can do it, I will share the files.

**Comment by golinmarq** [comment]
@wsorprendente in Laravel documentation you have an example. Here's the link https://laravel.com/docs/5.2/elixir
Read babel section
