### ISSUE TITLE
invalid credentials 

### ISSUE THREAD

**Issue by ProgrammedMikey** [onerciller/react-redux-laravel#3]
Hello, 

when i try postman login it return invalid credentials which makes it difficult to do anything without the token. In the database it is saving the registered user without encypting the password.

**Comment by onerciller** [comment]
hello, I understood your problem,  I write  part of API(backend) in basic level,it might be such errors on the API side since  I want to learn more redux.  I will check it and fix. thank you for report

**Comment by ProgrammedMikey** [comment]
Cool thanks for the reply! 
Yeah it's something with the api when logging in it returns "unable to parse token" when going to /api/userinfo. 

Also how would I deploy an app like this to heroku? Does the client side(client-app) need to be deployed to a different server im guessing?

**Comment by onerciller** [comment]
I think that react-redux will help you about how  it will  deploy at followings link, I need take a look for backend(api) errors, I will fix it as soon as possible
http://www.thegreatcodeadventure.com/deploying-react-redux-to-heroku/
you feel free keep asking, I will reply as much as  I can
