### ISSUE TITLE
Serving the client app?

### ISSUE THREAD

**Issue by baj84** [onerciller/react-redux-laravel#5]
Hey,

How is the client app meant to get served up? Laravel runs on http://localhost and points to /public/index.php but client_app/ is outside of this - how can it be accessed?

Thanks

**Comment by onerciller** [comment]
first of all, you should make npm install for client-app, afterwards , you should make npm start in client-app directory and you can access it from localhost:8080 port

**Comment by baj84** [comment]
Yeah, but when in production how can you run both the client and backend from the same server? 
Laravel serves everything from public/index.php, so you would have to somehow route it to your client-app/index.html...
