### ISSUE TITLE
issues when update composer in first step

### ISSUE THREAD

**Issue by Sarmed-armis** [onerciller/react-redux-laravel#6]
this is error in user\env syntax  
!/usr/bin/env php

?[37;41m                                                           ?[39;49m
?[37;41m  [Symfony\Component\Debug\Exception\FatalErrorException]  ?[39;49m
?[37;41m  syntax error, unexpected '}'                             ?[39;49m
?[37;41m                                                           ?[39;49m

**Comment by onerciller** [comment]
fixed
