### ISSUE TITLE
Tutorial/guide?

### ISSUE THREAD

**Issue by Noitidart** [onerciller/react-redux-laravel#9]
Hi there,

Is there a tutorial/guide to how to use this? My goal is to make my react-router, redux-form, react app (thats why this module of yours is so perfect for me) work so that react-router url's load server side with proper title (this is important for things like facebook link sharing and non-js rending web crawlers for seo) and first `ReactDOM.render` done. I don't want to use blade or any of laravel's stuff. Is there a guide showing how to do this?

**Comment by onerciller** [comment]
hi @Noitidart thanks for your comment, this project is not server side rendering  i would suggest you     research for [next js](https://github.com/zeit/next.js/) for server side rendering in react

**Comment by Noitidart** [comment]
Thanks sir for very fast reply and leaving topic open for me to close out. I will look into next js thanks for helping in correct direction! I use Laravel only for the REST API, I totally love it :)
